<?xml version="1.0" encoding="UTF-8"?>
<project name="HE176322_J1LP0015_AssetManagementEmployee" default="default" basedir=".">
    <description>Builds, tests, and runs the LAB211 project HE176322_J1LP0015_AssetManagementEmployee.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
